---
title: "R Notebook"
output: html_notebook
Pregunta: 3
---
```{r}
library(psych) 
library(knitr) 
library(kableExtra)
library(cluster)
library(plyr)
library(factoextra)
library(stringr)
library(magrittr)
library(htmltab)
library(readr)
library(rio)
library(dbscan)
library(ggrepel)
library(fpc)
library(dplyr)
library(foreign)
library(car)
```

```{r}
data2<-data
```

```{r}
data[,c(1,4,6,8,10,12,14,15)]=NULL
data[c(1:3,5:7,70,125,163,200,207:269),]=NULL
data=data[-c(1:3,5:7,70,125,163,200,207:269),]

names(data)=c("PAIS","HDI","naci","esco","esco2","GNI", "GNIHDI")

data=data[-c(1),]

	data[,c(2:7)]=lapply(data[,c(2:7)], as.numeric)
	
	str(data)
```


```{r}
row.names(data)=data$PAIS # cambiando row.names
demo=na.omit(demo)
set.seed(2020)
inputData=data[,c(2:7)]
inputData=na.omit(inputData)
g.dist = daisy(inputData, metric="gower")
```

```{r}
#PAM o Particiones
res.pam = pam(g.dist,4,cluster.only = F)
#AGNES o aglomerativa
res.agnes = hcut(g.dist, k = 4,hc_func='agnes',hc_method = "ward.D")
#DIANA o divisiva
res.diana = hcut(g.dist, k = 4,hc_func='diana')

#PAM
fviz_silhouette(res.pam)
#AGNES
fviz_silhouette(res.agnes)
#DIANA
fviz_silhouette(res.diana)

```

```{r}
#AGNES
poorAGNES=data.frame(res.agnes$silinfo$widths)
poorAGNES$country=row.names(poorAGNES)
poorAGNEScases=poorAGNES[poorAGNES$sil_width<0,'country']

#DIANA
poorDIANA=data.frame(res.diana$silinfo$widths)
poorDIANA$country=row.names(poorDIANA)
poorDIANAcases=poorDIANA[poorDIANA$sil_width<0,'country']

```

```{r}
# Revisamos c贸mo se ve ese elemento widths
head(res.agnes$silinfo$widths) 
# Creamos un data.frame que sea equivalente a ese elemento
widths.aglomerativo=data.frame(res.agnes$silinfo$widths)
# Creamos un vector que sea el nombre de la regi贸n. Lo jalamos del nombre de la fila.
widths.aglomerativo$Id=row.names(widths.aglomerativo)
# Creamos un objeto que sea los nombres de aquellos casos cuyos widths sean menor a 0. 
malos.widths.aglomerativo=widths.aglomerativo[widths.aglomerativo$sil_width<0,'Id']
malos.widths.aglomerativo
#cantidad de casos
length(malos.widths.aglomerativo)

```


```{r}
# Revisamos c贸mo se ve ese elemento widths
head(res.diana$silinfo$widths) 
# Creamos un data.frame que sea equivalente a ese elemento
widths.divisivo=data.frame(res.diana$silinfo$widths)
# Creamos un vector que sea el nombre de la regi贸n. Lo jalamos del nombre de la fila.
widths.divisivo$Id=row.names(widths.divisivo)
# Creamos un objeto que sea los nombres de aquellos casos cuyos widths sean menor a 0. 
malos.widths.divisivo=widths.divisivo[widths.divisivo$sil_width<0,'Id']
malos.widths.divisivo
#cantidad de casos
length(malos.widths.divisivo)
```



```{r}
row.names(data)=data$PAIS # cambiando row.names
demo=na.omit(demo)
set.seed(2020)
inputData1=data[,c(2:6)]
inputData1=na.omit(inputData1)
g.dist = daisy(inputData, metric="gower")
```

```{r}
#PAM o Particiones
res.pam = pam(g.dist,4,cluster.only = F)
#AGNES o aglomerativa
res.agnes = hcut(g.dist, k = 4,hc_func='agnes',hc_method = "ward.D")
#DIANA o divisiva
res.diana = hcut(g.dist, k = 4,hc_func='diana')

#PAM
fviz_silhouette(res.pam)
#AGNES
fviz_silhouette(res.agnes)
#DIANA
fviz_silhouette(res.diana)

```











