---
title: "R Notebook"
output: html_notebook
Pregunta: 4
---
```{r}
library(psych) 
library(knitr) 
library(kableExtra)
library(cluster)
library(plyr)
library(factoextra)
library(stringr)
library(magrittr)
library(htmltab)
library(readr)
library(rio)
library(dbscan)
library(ggrepel)
library(fpc)
library(dplyr)
library(foreign)
library(car)
```

```{r}
data[,c(1,4,6,8,10,12,14,15)]=NULL
data[c(1:3,5:7,70,125,163,200,207:269),]=NULL
data=data[-c(1:3,5:7,70,125,163,200,207:269),]

names(data)=c("PAIS","HDI","naci","esco","esco2","GNI", "GNIHDI")

data=data[-c(1),]

	data[,c(2:7)]=lapply(data[,c(2:7)], as.numeric)
	
	str(data)
```

```{r}
row.names(data)=data$PAIS # cambiando row.names
demo=na.omit(demo)
set.seed(2020)
inputData1=data[,c(2:6)]
inputData1=na.omit(inputData1)
g.dist = daisy(inputData1, metric="gower")
```

```{r}
#PAM o Particiones
res.pam = pam(g.dist,4,cluster.only = F)
#AGNES o aglomerativa
res.agnes = hcut(g.dist, k = 4,hc_func='agnes',hc_method = "ward.D")
#DIANA o divisiva
res.diana = hcut(g.dist, k = 4,hc_func='diana')

#PAM
fviz_silhouette(res.pam)
#AGNES
fviz_silhouette(res.agnes)
#DIANA
fviz_silhouette(res.diana)

```


```{r}
inputData1$diana=as.factor(res.diana$cluster)
```

































