---
title: "R Notebook"
output: html_notebook
Pregunta: 5
---
```{r}
library(psych) 
library(knitr) 
library(kableExtra)
library(cluster)
library(plyr)
library(factoextra)
library(stringr)
library(magrittr)
library(htmltab)
library(readr)
library(rio)
library(dbscan)
library(ggrepel)
library(fpc)
library(dplyr)
library(foreign)
library(car)
```

```{r}
library(htmltab)
	linkpage="https://en.wikipedia.org/wiki/List_of_freedom_indices"
	linkpath='//*[@id="mw-content-text"]/div[1]/table[2]'
	data=htmltab(doc=linkpage, which=linkpath)
```

```{r}
str(data)

table(data)
      ##
data=na.omit(data)

names(data)=c("Pais", "LM", "LE", "LP", "ID")

data$Pais=gsub("Â", "", data$Pais)
names(data)=gsub(" ", "", names(data))

#Libertad mundial 
table(data$LM)
data$LM=as.factor(data$LM)
#data$LM=as.numeric(data$LM)
table(data$LM)


library(dplyr)
#recode
#primero va lo real luego lo que recodificamos
data$LM=recode(data$LM, 
               'free'='3free',
               'partly free'='2partlyfree',
               'not free'='1notfree' ,
               'n/a'='NA')
str(data)
```

```{r}
table(data$LE)
data$LE=as.factor(data$LE)
data$LE=recode(data$LE, 
               'free'='5free',
               'moderately free'='4moderatelyfree',
               'mostlyfree'='3mostlyfree',
               'repressed'='1repressed',
               'mostly unfree'='2mostlyunfree' ,
               'n/a'='NA')
str(data)
```

```{r}
table(data$LP)
data$LP=as.factor(data$LP)
data$LP=recode(data$LP, 
               'difficult situation'='1difficult situation',
               'noticeable problems'='2noticeable problems',
               'very serious situation'='3very serious situation',
               'good situation'='4good situation',
               'satisfactory situation'='5satisfactory situation' ,
               'n/a'='NA')
str(data)
```

```{r}
table(data$ID)
data$ID=as.factor(data$ID)
data$ID=recode(data$ID, 
               'authoritarian regime'='1authoritarian regime',
               'flawed democracy'='2flawed democracy',
               'full democracy'='3full democracy',
               'hybrid regime'='4hybrid regime',
               'n/a'='NA')
str(data)
```

```{r}
row.names(data)=demo$Pais # cambiando row.names
data=na.omit(data)
set.seed(2020)
inputData=data[,c(2:4)]
g.dist = daisy(inputData, metric="gower")
```

```{r}
proyeccion = cmdscale(g.dist, k=2,add = T) # k is the number of dim

inputData$dim1 <- proyeccion$points[,1]
inputData$dim2 <- proyeccion$points[,2]

base= ggplot(inputData,aes(x=dim1, y=dim2,label=row.names(inputData))) 
base + geom_text(size=2)
```

```{r}
min(inputData[,c('dim1','dim2')]); max(inputData[,c('dim1','dim2')])
```

```{r}
limites=c(-1.3,1.3)
```

```{r}
g.dist.cmd = daisy(inputData[,c('dim1','dim2')], metric = 'euclidean')

library(dbscan)
kNNdistplot(g.dist.cmd, k=4)

library(fpc)
db.cmd = dbscan(g.dist.cmd, eps=0.13, MinPts=3,method = 'dist')
db.cmd
inputData$dbCMD=as.factor(db.cmd$cluster)
```












